version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    container_name: bill-app-web
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: on-failure:3
    depends_on:
      - db
      - pgadmin

volumes:
  postgres_data: