"""added fk

Revision ID: 182249a3fc87
Revises: 
Create Date: 2024-04-06 13:39:45.003679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182249a3fc87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bills_id', table_name='bills')
    op.drop_table('bills')
    op.drop_index('ix_sub_bills_id', table_name='sub_bills')
    op.drop_table('sub_bills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_bills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sub_bills_pkey'),
    sa.UniqueConstraint('reference', name='sub_bills_reference_key')
    )
    op.create_index('ix_sub_bills_id', 'sub_bills', ['id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bills_pkey')
    )
    op.create_index('ix_bills_id', 'bills', ['id'], unique=False)
    # ### end Alembic commands ###
